### ISSUE TITLE
Tokenization seems to be broken

### ISSUE THREAD

**Issue by ctschroeder** [gucorpling/gitdox#120]
I tried tokenizing johannes.canons.FA143-158 in GitDox and nothing happened.

Then I copied and pasted a couple lines of text into a new document, changed the milestone tags to wrapped tags, and tried again.  After clicking the tokenize button all the text disappeared from the window.  (Yikes!)

I went back to the document menu and clicked on the document again. Text was there but still not tokenized.

I think I would classify this bug as urgent.

Thanks.

**Comment by amir-zeldes** [comment]
I can reproduce, this is an urgent bug. @lgessler : this happens when running the Coptic tokenizer in XML mode from GitDox. I was able to verify that everything runs correctly down to `render_data['text_content'] = text_content` here, where text_content now correctly contains the result of tokenization, so it's not the NLP service:

https://github.com/gucorpling/gitdox/blob/master/editor.py#L373

It seems the Renderer in render() is somehow not populating the CodeMirror textarea correctly, and it ends up containing whatever is in the DB rather than accepting the new content from the tokenizer API call. Can you take a look at the pystache data model and why it might not be updating from the requests response? 

(The best way might be to print debug values into a file while running on /var/www/html/gitdox/scriptorium - hitting tokenize in document editor.py?id=154 will produce the bug)

**Comment by amir-zeldes** [comment]
@ctschroeder it would be good if you could leave this document alone for Luke to test on, but if you have other docs to work on in parallel, running the tokenizer on the NLP page and pasting the result should work as a quick fix.

**Comment by ctschroeder** [comment]
Thanks for the speedy reply! Yes, I was going to continue this afternoon by cutting and pasting into the stand alone NLP web tool but will use another document. Good luck!

**Comment by lgessler** [comment]
Haven't been able to test on the scriptorium instance because of lack of permissions but I'm pretty sure #121 should fix this.

**Comment by amir-zeldes** [comment]
Just tested, unfortunately it still won't insert the tokenized content into the textarea. The files are owned by apache and are group writable, so I've added you to the apache group. You should be able to test now, but if not just let me know!

**Comment by lgessler** [comment]
Found the issue, d2ff1fe hasn't made its way into master and the buggy hack was causing tokenization to appear not to work. I made the change in d2ff1fe in prod and the bug disappeared.
